### ISSUE TITLE
Add wider team members onto team page

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/website-redesign#112]
- Beth
- Israa
- Cemal
- Kristina

@Israa91 and @fadeomar to lead on collecting photos from everyone and adding them to site

**Comment by fadeomar** [comment]
hey @cyberteenie we are waiting for @bethanyios , @Israa91 , @cemalokten , and you @cyberteenie to add a photo here or on discord channel.
also for the rest of the team how want to update his/her photo on the website me @RamyAlshurafa @thejoefriel and @ashatat and @jema28 would be nice too

**Comment by fadeomar** [comment]
hey @cyberteenie no guidelines but formal photo like Ramy or Joe here https://www.yallacooperative.com/our-story

**Comment by bethanyios** [comment]
<img width="508" alt="bs-profile" src="https://user-images.githubusercontent.com/36175966/157264288-2faa84d6-df53-42ad-afc2-bf07a57ca927.png">

![bs-profile2](https://user-images.githubusercontent.com/36175966/157264334-2b28a105-2bb9-42e4-a205-fa49391a2e56.jpeg)

Hi @fadeomar are either of these okay? I dont have normal access to all my photos.
