### ISSUE TITLE
Agree on tech stack

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/website-redesign#12]
Hey @jema28 @thejoefriel @dupreesi @ashatat 
it would be great to get your inputs to choose what do we need to use from these options:

- Static pages generators (one of):
  - [x] Gatsby
  - [ ] Webflow
  - [ ] pure React
- CMS (headless) :
  - [ ] Netlify
  - [ ] Wordpress
  - [ ] Sanity
- UI test:
  - [ ] cypress
  - [ ] puppeteer
- others: 
  - [x] storybook

**Comment by jema28** [comment]
After discussing with @RamyAlshurafa, we're thinking gatsby would be a good choice for this project. As a starter template including a style guide, I've suggested using this repo https://github.com/jema28/what-im-learning (a workshop I created to design week in Gaza). Also, we don't think it's necessary to include a CMS as the content in case studies may be structured differently and may be overkill. 

Would also be great to try out storybook or Bit so we can use this in other projects.

**Comment by Amoodaa** [comment]
Suggesting new stuff for the tech stack:
- [ ] styled-components
- [ ] (Mdx)[https://mdxjs.com/]
- [ ] Decide how we want to make new blogs (considering the option of mdx( markdown along side our custom components) or not mdx (json objects that can be rendered or wanting to write plain react pages using reusable components))

**Comment by Amoodaa** [comment]
After agreeing this issue is closed
