### ISSUE TITLE
Building components: create inputs

### ISSUE THREAD

**Issue by jema28** [yalla-coop/website-redesign#21]
### Create the inputs
We have one input component in our design but it can look different according to its size:

1. **Normal Input Field**

![Imgur](https://i.imgur.com/nJpglWx.png)

**Main Props**:
- Type (email, phone, text, etc)
- Size (large, normal)
- Label 
- Placeholder
- Value
- OnChange Function
- Error (so there should be some validation)
  - **Email**: Please provide a valid email address
  - **Phone**: Please provide a valid phone number

**Main Styles**:
- Label (Caps Heading Small Component)
- Placeholder/text (Input Placeholder Text Component)
- Input box/field
```css 
/* we might use the variables we have in the utils folder  */
  padding: 16px;
  margin-top: 6px; /* between the label and the box */
  background: rgba(196, 196, 196, 0.05);
  border: 1px solid rgba(224, 224, 224, 0.5);
```

2. **Large Input Field**:

![Large](https://user-images.githubusercontent.com/44949822/76195176-6c957180-61f0-11ea-8a00-76c4ffa170d2.png)

To this one, you can apply all of the above but the width and height should be bigger for the **input box** as you can see

```css
/* these will not be static forever */
  width: 674px; 
  height: 227px;
```

**Comment by fadeomar** [comment]
if you want to input text in multiline you probably need for textarea element, not input because the input doesn't wrap the text 

src : https://stackoverflow.com/questions/5286663/wrapping-text-inside-input-type-text-element-html-css

**Comment by yosefanajjar** [comment]
okay then you can make it as a text area but I think you can manage that in the same component still, like having a `type` prop. What do you think?
