### ISSUE TITLE
Building components: subtitle

### ISSUE THREAD

**Issue by yosefanajjar** [yalla-coop/website-redesign#40]
### Create subtitle with accent 
![Subtitle](https://user-images.githubusercontent.com/44949822/76454652-b2635d00-63dd-11ea-9900-e0d64c78696d.png)

**Comment by fadeomar** [comment]
the common subtitle component is in large size 
for example : 
in contect us page : 
![Screenshot from 2020-03-21 18-41-56](https://user-images.githubusercontent.com/39485495/77231457-b2184e00-6ba3-11ea-90b6-edceb14a46b3.png)

and in our approach page : 
![Screenshot from 2020-03-21 18-43-43](https://user-images.githubusercontent.com/39485495/77231494-fd326100-6ba3-11ea-9f09-756854a3b781.png)

and for the picture you posted above it look like small one 

so for that component shuold take a prop as size for small or large one 
and it take a 100% width and we can control it when we call the component by detrmine the parent width
