### ISSUE TITLE
Build Our Story + Team page and make it responsive 

### ISSUE THREAD

**Issue by yosefanajjar** [yalla-coop/website-redesign#65]
Figma : https://www.figma.com/file/e7lI7XGEGvCAxKcnktUfkt/Yalla-Website-Redesign?node-id=1307%3A32849

**Comment by jema28** [comment]
**Mobile - Small**
- [ ] Header
- [ ] Introduction
- [ ] Our Team
_Common Interested in working with us section / Footer_

**Mobile - Medium**
- [ ] Header
- [ ] Introduction
- [ ] Our Team
_Common Interested in working with us section / Footer_

**Mobile - Large / Tablet**:
- [ ] Header
- [ ] Introduction
- [ ] Our Team
_Common Interested in working with us section / Footer_

**Laptop**:
- [ ] Header
- [ ] Introduction
- [ ] Our Team
_Common Interested in working with us section / Footer_
