### ISSUE TITLE
Make header component responsive 

### ISSUE THREAD

**Issue by yosefanajjar** [yalla-coop/website-redesign#70]
### Sections

- [x] Make headers responsive on:
   - [x] Landing page
      - [x] mobileSmall
      - [x] mobileMedium
      - [x] mobileLarge / tablet
      - [x] laptop / desktop
   - [x] Our Approach + Services page
      - [x] mobileSmall
      - [x] mobileMedium
      - [x] mobileLarge / tablet
      - [x] laptop / desktop
   - [x] earwig case study
      - [x] mobileSmall
      - [x] mobileMedium
      - [x] mobileLarge / tablet
      - [x] laptop / desktop
   - [x] PressPad case study
      - [x] mobileSmall
      - [x] mobileMedium
      - [x] mobileLarge / tablet
      - [x] laptop / desktop

**Comment by jema28** [comment]
Headers included in the separate page issues so going to close this. The template I made for the ones above can be used for the rest of the pages.
